// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvHNQa6SFSIlkcx_HlLDpYmB-4sc6Azhk',
    appId: '1:1028168208865:web:856bde1f1c7ee3092242a0',
    messagingSenderId: '1028168208865',
    projectId: 'newchatapp-13b6b',
    authDomain: 'newchatapp-13b6b.firebaseapp.com',
    storageBucket: 'newchatapp-13b6b.appspot.com',
    measurementId: 'G-R5EN0H8W85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIqAm6dVMquZSm4802SoN6GwmkJXl_A-U',
    appId: '1:1028168208865:android:1af5d0c8313a00952242a0',
    messagingSenderId: '1028168208865',
    projectId: 'newchatapp-13b6b',
    storageBucket: 'newchatapp-13b6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9JcuNjYL2ifDE3E417vlW6bHywOBOD9E',
    appId: '1:1028168208865:ios:137802770751309d2242a0',
    messagingSenderId: '1028168208865',
    projectId: 'newchatapp-13b6b',
    storageBucket: 'newchatapp-13b6b.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9JcuNjYL2ifDE3E417vlW6bHywOBOD9E',
    appId: '1:1028168208865:ios:137802770751309d2242a0',
    messagingSenderId: '1028168208865',
    projectId: 'newchatapp-13b6b',
    storageBucket: 'newchatapp-13b6b.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvHNQa6SFSIlkcx_HlLDpYmB-4sc6Azhk',
    appId: '1:1028168208865:web:68a8b9ac0ab6ae512242a0',
    messagingSenderId: '1028168208865',
    projectId: 'newchatapp-13b6b',
    authDomain: 'newchatapp-13b6b.firebaseapp.com',
    storageBucket: 'newchatapp-13b6b.appspot.com',
    measurementId: 'G-3SVMS8CHT8',
  );
}
